name: Terraform Validation

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  tflint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run TFLint Composite Action
        uses: datalush/tf-validation/actions/tflint@main

      - name: Run TFSec
        uses: datalush/tf-validation/actions/tfsec@main